# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='location',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
