# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-19 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_host_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_status_id',
            field=models.IntegerField(choices=[(1, '启用'), (2, '挂起'), (3, '停用')], default=1),
        ),
    ]
