# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-19 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_host_host_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='location',
        ),
        migrations.AddField(
            model_name='host',
            name='a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Area'),
            preserve_default=False,
        ),
    ]
