# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190619_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='type_id',
            field=models.IntegerField(choices=[(1, '开发'), (2, '测试'), (3, '管理员')], default=1),
        ),
    ]
